CREATE TABLE CLIENTE (
    COD_CLIENTE INT NOT NULL AUTO_INCREMENT ,
    PRIMER_NOMBRE       VARCHAR(255) NOT NULL,
    SEGUNDO_NOMBRE      VARCHAR(255),
    PRIMER_APELLIDO     VARCHAR(255),
    SEGUNDO_APELLIDO    VARCHAR(255),
    DOC_IDENTIDAD       VARCHAR(255) NOT NULL,
    EMAIL               VARCHAR(255) NOT NULL,
    USUARIO             VARCHAR(255) NOT NULL,
    HASHPASS            VARCHAR(255) NOT NULL,
    PRIMARY KEY (COD_CLIENTE),  
    CONSTRAINT UNI_CLIENTE UNIQUE (DOC_IDENTIDAD,EMAIL,USUARIO)
);


CREATE TABLE PRODUCTO (
    COD_PRODUCTO       INT NOT NULL AUTO_INCREMENT,
    NOMBRE             VARCHAR(255) NOT NULL,
    DESCRIPCION        VARCHAR(255),
    PRECIO             DECIMAL(8,2) NOT NULL,
    CODIGO_BARRAS      VARCHAR(50) NOT NULL,
    PRIMARY KEY (COD_PRODUCTO),
    CONSTRAINT UNI_PRODUCTO UNIQUE(CODIGO_BARRAS)

);


CREATE TABLE TIENDA (
    COD_TIENDA       INT NOT NULL AUTO_INCREMENT,
    NOMBRE           VARCHAR(255) NOT NULL,
    HORARIO          VARCHAR(255) NOT NULL,
    DIRECCION        VARCHAR(255) NOT NULL,
    PRIMARY KEY(COD_TIENDA)
);



CREATE TABLE TIENDA_PRODUCTO(
    COD_TIENDA      INT NOT NULL,
    COD_PRODUCTO    INT NOT NULL,
    CANTIDAD        INT NOT NULL
);

ALTER TABLE TIENDA_PRODUCTO
ADD CONSTRAINT FK_TIENDA_PRODUCTO_T
FOREIGN KEY (COD_TIENDA) REFERENCES TIENDA(COD_TIENDA); 


ALTER TABLE TIENDA_PRODUCTO
ADD CONSTRAINT FK_PRODUCTO_TIENDA_P
FOREIGN KEY (COD_PRODUCTO) REFERENCES PRODUCTO(COD_PRODUCTO);


CREATE TABLE VENTA_CLIENTE (
    COD_CLIENTE     INT NOT NULL,
    COD_PRODUCTO    INT NOT NULL,
    FECHA_VENTA     DATE NOT NULL
);

ALTER TABLE VENTA_CLIENTE
ADD CONSTRAINT FK_CLIENTE_VENTA
FOREIGN KEY (COD_CLIENTE) REFERENCES CLIENTE(COD_CLIENTE);


ALTER TABLE VENTA_CLIENTE
ADD CONSTRAINT FK_PRODUCTO_VENTA
FOREIGN KEY (COD_PRODUCTO) REFERENCES PRODUCTO(COD_PRODUCTO);
