CREATE TABLE CLIENTE (
    COD_CLIENTE INT NOT NULL AUTOINCREMENT ,
    PRIMER_NOMBRE       VARCHAR(255) NOT NULL,
    SEGUNDO_NOMBRE      VARCHAR(255),
    PRIMER_APELLIDO     VARCHAR(255),
    SEGUNDO_APELLIDO    VARCHAR(255),
    DOC_IDENTIDAD       VARCHAR(255) NOT NULL,
    EMAIL               VARCHAR(255) NOT NULL,
    USUARIO             VARCHAR(255) NOT NULL,
    HASHPASS            VARCHAR(255) NOT NULL,
    PRIMARY KEY (COD_CLIENTE),  
    CONSTRAINT UNI_CLIENTE UNIQUE (DOC_IDENTIDAD,EMAIL,USUARIO)
);


CREATE TABLE PRODUCTO (
    COD_PRODUCTO       INT NOT NULL AUTOINCREMENT,
    NOMBRE             VARCHAR(255) NOT NULL,
    DESCRIPCION        VARCHAR(255),
    PRECIO             DECIMAL(8,2) NOT NULL,
    CODIGO_BARRAS      VARCHAR(50) NOT NULL,
    PRIMARY KEY (COD_PRODUCTO),
    CONSTRAINT UNI_PRODUCTO UNIQUE(CODIGO_BARRAS)

);